"""
Flyway presets for major bird migration routes.

Each preset provides default corridor definitions, species groups, and
monthly calendars tuned for a particular flyway region. Researchers
select a preset when generating a config from turbine CSV data.
"""

from __future__ import annotations

from typing import Any, Dict

FLYWAY_PRESETS: Dict[str, Dict[str, Any]] = {
    "atlantic": {
        "label": "Atlantic Flyway (Eastern North America)",
        "corridors": [
            {
                "name": "Atlantic NE-SW coastal",
                "angle_deg": 225,
                "sigma": 0.11,
                "curvature": 0.05,
                "species": ["songbirds", "waterfowl"],
                "weight_spring": 0.50,
                "weight_fall": 0.55,
                "weight_default": 0.50,
            },
            {
                "name": "Atlantic N-S raptor ridge",
                "angle_deg": 180,
                "sigma": 0.08,
                "curvature": 0.03,
                "species": ["raptors"],
                "weight_spring": 0.45,
                "weight_fall": 0.60,
                "weight_default": 0.48,
            },
        ],
        "species": {
            "songbirds": {
                "label": "Songbirds (warblers/sparrows)",
                "color": [255, 165, 0],
                "color_pub": [230, 150, 40],
                "arrow_count": 55,
                "sigma": 18,
                "arrow_width": 5,
                "arrow_length": 58,
                "alpha": 150,
            },
            "waterfowl": {
                "label": "Waterfowl / shorebirds",
                "color": [60, 200, 255],
                "color_pub": [80, 170, 210],
                "arrow_count": 45,
                "sigma": 14,
                "arrow_width": 5,
                "arrow_length": 56,
                "alpha": 150,
            },
            "raptors": {
                "label": "Raptors (hawks/eagles)",
                "color": [255, 60, 60],
                "color_pub": [210, 80, 80],
                "arrow_count": 26,
                "sigma": 10,
                "arrow_width": 6,
                "arrow_length": 64,
                "alpha": 160,
            },
            "local": {
                "label": "Local/resident birds",
                "color": [60, 255, 140],
                "color_pub": [90, 210, 150],
            },
        },
        "monthly_calendar": [
            {"month": "Jan", "migration_index": 0.05, "intensity": 0.10, "label": "Winter: low activity", "season": "winter"},
            {"month": "Feb", "migration_index": 0.05, "intensity": 0.12, "label": "Winter: low activity", "season": "winter"},
            {"month": "Mar", "migration_index": 0.30, "intensity": 0.40, "label": "Spring build-up", "season": "spring"},
            {"month": "Apr", "migration_index": 0.70, "intensity": 0.85, "label": "Spring: northbound peak", "season": "spring"},
            {"month": "May", "migration_index": 0.80, "intensity": 1.00, "label": "Spring: northbound peak", "season": "spring"},
            {"month": "Jun", "migration_index": 0.15, "intensity": 0.20, "label": "Summer: low migration", "season": "summer"},
            {"month": "Jul", "migration_index": 0.10, "intensity": 0.15, "label": "Summer: low migration", "season": "summer"},
            {"month": "Aug", "migration_index": 0.35, "intensity": 0.35, "label": "Late summer ramp-up", "season": "summer"},
            {"month": "Sep", "migration_index": 0.65, "intensity": 0.85, "label": "Fall: southbound peak", "season": "fall"},
            {"month": "Oct", "migration_index": 0.85, "intensity": 1.00, "label": "Fall: southbound peak", "season": "fall"},
            {"month": "Nov", "migration_index": 0.28, "intensity": 0.45, "label": "Fall winding down", "season": "fall"},
            {"month": "Dec", "migration_index": 0.06, "intensity": 0.10, "label": "Winter: low activity", "season": "winter"},
        ],
    },

    "mississippi": {
        "label": "Mississippi Flyway (Central North America)",
        "corridors": [
            {
                "name": "Mississippi N-S main",
                "angle_deg": 175,
                "sigma": 0.12,
                "curvature": 0.04,
                "species": ["songbirds", "waterfowl"],
                "weight_spring": 0.55,
                "weight_fall": 0.60,
                "weight_default": 0.52,
            },
            {
                "name": "Mississippi N-S raptor",
                "angle_deg": 185,
                "sigma": 0.09,
                "curvature": 0.02,
                "species": ["raptors"],
                "weight_spring": 0.50,
                "weight_fall": 0.55,
                "weight_default": 0.48,
            },
        ],
        "species": {
            "songbirds": {
                "label": "Songbirds (warblers/thrushes)",
                "color": [255, 165, 0],
                "color_pub": [230, 150, 40],
                "arrow_count": 55,
                "sigma": 18,
                "arrow_width": 5,
                "arrow_length": 58,
                "alpha": 150,
            },
            "waterfowl": {
                "label": "Waterfowl (ducks/geese)",
                "color": [60, 200, 255],
                "color_pub": [80, 170, 210],
                "arrow_count": 50,
                "sigma": 16,
                "arrow_width": 5,
                "arrow_length": 56,
                "alpha": 150,
            },
            "raptors": {
                "label": "Raptors (hawks/eagles)",
                "color": [255, 60, 60],
                "color_pub": [210, 80, 80],
                "arrow_count": 26,
                "sigma": 10,
                "arrow_width": 6,
                "arrow_length": 64,
                "alpha": 160,
            },
            "local": {
                "label": "Local/resident birds",
                "color": [60, 255, 140],
                "color_pub": [90, 210, 150],
            },
        },
        "monthly_calendar": [
            {"month": "Jan", "migration_index": 0.05, "intensity": 0.10, "label": "Winter", "season": "winter"},
            {"month": "Feb", "migration_index": 0.03, "intensity": 0.12, "label": "Winter", "season": "winter"},
            {"month": "Mar", "migration_index": 0.25, "intensity": 0.40, "label": "Spring build-up", "season": "spring"},
            {"month": "Apr", "migration_index": 0.70, "intensity": 0.85, "label": "Spring peak", "season": "spring"},
            {"month": "May", "migration_index": 0.80, "intensity": 1.00, "label": "Spring peak", "season": "spring"},
            {"month": "Jun", "migration_index": 0.18, "intensity": 0.20, "label": "Summer", "season": "summer"},
            {"month": "Jul", "migration_index": 0.12, "intensity": 0.15, "label": "Summer", "season": "summer"},
            {"month": "Aug", "migration_index": 0.40, "intensity": 0.35, "label": "Late summer", "season": "summer"},
            {"month": "Sep", "migration_index": 0.65, "intensity": 0.85, "label": "Fall peak", "season": "fall"},
            {"month": "Oct", "migration_index": 0.85, "intensity": 1.00, "label": "Fall peak", "season": "fall"},
            {"month": "Nov", "migration_index": 0.28, "intensity": 0.45, "label": "Fall winding down", "season": "fall"},
            {"month": "Dec", "migration_index": 0.06, "intensity": 0.10, "label": "Winter", "season": "winter"},
        ],
    },

    "central": {
        "label": "Central Flyway (Great Plains)",
        "corridors": [
            {
                "name": "Central N-S prairie",
                "angle_deg": 180,
                "sigma": 0.13,
                "curvature": 0.03,
                "species": ["songbirds", "waterfowl"],
                "weight_spring": 0.50,
                "weight_fall": 0.55,
                "weight_default": 0.50,
            },
            {
                "name": "Central N-S raptor",
                "angle_deg": 175,
                "sigma": 0.09,
                "curvature": 0.02,
                "species": ["raptors"],
                "weight_spring": 0.48,
                "weight_fall": 0.52,
                "weight_default": 0.48,
            },
        ],
        "species": {
            "songbirds": {
                "label": "Songbirds (sparrows/buntings)",
                "color": [255, 165, 0],
                "color_pub": [230, 150, 40],
                "arrow_count": 50,
                "sigma": 18,
                "arrow_width": 5,
                "arrow_length": 58,
                "alpha": 150,
            },
            "waterfowl": {
                "label": "Waterfowl (ducks/cranes)",
                "color": [60, 200, 255],
                "color_pub": [80, 170, 210],
                "arrow_count": 50,
                "sigma": 16,
                "arrow_width": 5,
                "arrow_length": 56,
                "alpha": 150,
            },
            "raptors": {
                "label": "Raptors (hawks/eagles)",
                "color": [255, 60, 60],
                "color_pub": [210, 80, 80],
                "arrow_count": 24,
                "sigma": 10,
                "arrow_width": 6,
                "arrow_length": 64,
                "alpha": 160,
            },
            "local": {
                "label": "Local/resident birds",
                "color": [60, 255, 140],
                "color_pub": [90, 210, 150],
            },
        },
        "monthly_calendar": [
            {"month": "Jan", "migration_index": 0.04, "intensity": 0.08, "label": "Winter", "season": "winter"},
            {"month": "Feb", "migration_index": 0.04, "intensity": 0.10, "label": "Winter", "season": "winter"},
            {"month": "Mar", "migration_index": 0.30, "intensity": 0.42, "label": "Spring build-up", "season": "spring"},
            {"month": "Apr", "migration_index": 0.72, "intensity": 0.88, "label": "Spring peak", "season": "spring"},
            {"month": "May", "migration_index": 0.78, "intensity": 0.95, "label": "Spring peak", "season": "spring"},
            {"month": "Jun", "migration_index": 0.15, "intensity": 0.18, "label": "Summer", "season": "summer"},
            {"month": "Jul", "migration_index": 0.10, "intensity": 0.14, "label": "Summer", "season": "summer"},
            {"month": "Aug", "migration_index": 0.38, "intensity": 0.38, "label": "Late summer", "season": "summer"},
            {"month": "Sep", "migration_index": 0.68, "intensity": 0.88, "label": "Fall peak", "season": "fall"},
            {"month": "Oct", "migration_index": 0.82, "intensity": 0.98, "label": "Fall peak", "season": "fall"},
            {"month": "Nov", "migration_index": 0.25, "intensity": 0.40, "label": "Fall winding down", "season": "fall"},
            {"month": "Dec", "migration_index": 0.05, "intensity": 0.08, "label": "Winter", "season": "winter"},
        ],
    },

    "pacific": {
        "label": "Pacific Flyway (Western North America)",
        "corridors": [
            {
                "name": "Pacific coastal NW-SE",
                "angle_deg": 155,
                "sigma": 0.10,
                "curvature": 0.06,
                "species": ["songbirds", "waterfowl"],
                "weight_spring": 0.48,
                "weight_fall": 0.58,
                "weight_default": 0.50,
            },
            {
                "name": "Pacific inland raptor",
                "angle_deg": 170,
                "sigma": 0.08,
                "curvature": 0.03,
                "species": ["raptors"],
                "weight_spring": 0.50,
                "weight_fall": 0.55,
                "weight_default": 0.48,
            },
        ],
        "species": {
            "songbirds": {
                "label": "Songbirds (flycatchers/warblers)",
                "color": [255, 165, 0],
                "color_pub": [230, 150, 40],
                "arrow_count": 50,
                "sigma": 16,
                "arrow_width": 5,
                "arrow_length": 56,
                "alpha": 150,
            },
            "waterfowl": {
                "label": "Waterfowl / shorebirds",
                "color": [60, 200, 255],
                "color_pub": [80, 170, 210],
                "arrow_count": 45,
                "sigma": 14,
                "arrow_width": 5,
                "arrow_length": 56,
                "alpha": 150,
            },
            "raptors": {
                "label": "Raptors (hawks/falcons)",
                "color": [255, 60, 60],
                "color_pub": [210, 80, 80],
                "arrow_count": 22,
                "sigma": 10,
                "arrow_width": 6,
                "arrow_length": 62,
                "alpha": 160,
            },
            "local": {
                "label": "Local/resident birds",
                "color": [60, 255, 140],
                "color_pub": [90, 210, 150],
            },
        },
        "monthly_calendar": [
            {"month": "Jan", "migration_index": 0.06, "intensity": 0.12, "label": "Winter", "season": "winter"},
            {"month": "Feb", "migration_index": 0.08, "intensity": 0.15, "label": "Winter", "season": "winter"},
            {"month": "Mar", "migration_index": 0.35, "intensity": 0.45, "label": "Spring build-up", "season": "spring"},
            {"month": "Apr", "migration_index": 0.65, "intensity": 0.80, "label": "Spring peak", "season": "spring"},
            {"month": "May", "migration_index": 0.75, "intensity": 0.92, "label": "Spring peak", "season": "spring"},
            {"month": "Jun", "migration_index": 0.15, "intensity": 0.18, "label": "Summer", "season": "summer"},
            {"month": "Jul", "migration_index": 0.12, "intensity": 0.15, "label": "Summer", "season": "summer"},
            {"month": "Aug", "migration_index": 0.40, "intensity": 0.40, "label": "Late summer", "season": "summer"},
            {"month": "Sep", "migration_index": 0.70, "intensity": 0.88, "label": "Fall peak", "season": "fall"},
            {"month": "Oct", "migration_index": 0.80, "intensity": 0.95, "label": "Fall peak", "season": "fall"},
            {"month": "Nov", "migration_index": 0.30, "intensity": 0.48, "label": "Fall winding down", "season": "fall"},
            {"month": "Dec", "migration_index": 0.08, "intensity": 0.12, "label": "Winter", "season": "winter"},
        ],
    },

    "western_palearctic": {
        "label": "Western Palearctic (Europe/Africa)",
        "corridors": [
            {
                "name": "W. Palearctic NE-SW",
                "angle_deg": 210,
                "sigma": 0.12,
                "curvature": 0.05,
                "species": ["songbirds", "waterfowl"],
                "weight_spring": 0.50,
                "weight_fall": 0.55,
                "weight_default": 0.50,
            },
            {
                "name": "W. Palearctic raptor soaring",
                "angle_deg": 195,
                "sigma": 0.07,
                "curvature": 0.04,
                "species": ["raptors"],
                "weight_spring": 0.52,
                "weight_fall": 0.58,
                "weight_default": 0.50,
            },
        ],
        "species": {
            "songbirds": {
                "label": "Passerines (warblers/flycatchers)",
                "color": [255, 165, 0],
                "color_pub": [230, 150, 40],
                "arrow_count": 55,
                "sigma": 18,
                "arrow_width": 5,
                "arrow_length": 58,
                "alpha": 150,
            },
            "waterfowl": {
                "label": "Waterfowl / waders",
                "color": [60, 200, 255],
                "color_pub": [80, 170, 210],
                "arrow_count": 45,
                "sigma": 14,
                "arrow_width": 5,
                "arrow_length": 56,
                "alpha": 150,
            },
            "raptors": {
                "label": "Raptors (buzzards/harriers)",
                "color": [255, 60, 60],
                "color_pub": [210, 80, 80],
                "arrow_count": 28,
                "sigma": 10,
                "arrow_width": 6,
                "arrow_length": 64,
                "alpha": 160,
            },
            "local": {
                "label": "Local/resident birds",
                "color": [60, 255, 140],
                "color_pub": [90, 210, 150],
            },
        },
        "monthly_calendar": [
            {"month": "Jan", "migration_index": 0.04, "intensity": 0.08, "label": "Winter", "season": "winter"},
            {"month": "Feb", "migration_index": 0.06, "intensity": 0.12, "label": "Winter", "season": "winter"},
            {"month": "Mar", "migration_index": 0.35, "intensity": 0.48, "label": "Spring build-up", "season": "spring"},
            {"month": "Apr", "migration_index": 0.75, "intensity": 0.90, "label": "Spring peak", "season": "spring"},
            {"month": "May", "migration_index": 0.70, "intensity": 0.88, "label": "Spring peak", "season": "spring"},
            {"month": "Jun", "migration_index": 0.12, "intensity": 0.15, "label": "Summer", "season": "summer"},
            {"month": "Jul", "migration_index": 0.08, "intensity": 0.12, "label": "Summer", "season": "summer"},
            {"month": "Aug", "migration_index": 0.35, "intensity": 0.38, "label": "Late summer", "season": "summer"},
            {"month": "Sep", "migration_index": 0.72, "intensity": 0.90, "label": "Fall peak", "season": "fall"},
            {"month": "Oct", "migration_index": 0.80, "intensity": 0.95, "label": "Fall peak", "season": "fall"},
            {"month": "Nov", "migration_index": 0.25, "intensity": 0.40, "label": "Fall winding down", "season": "fall"},
            {"month": "Dec", "migration_index": 0.05, "intensity": 0.08, "label": "Winter", "season": "winter"},
        ],
    },

    "east_asian": {
        "label": "East Asian-Australasian Flyway",
        "corridors": [
            {
                "name": "East Asian N-S coastal",
                "angle_deg": 185,
                "sigma": 0.11,
                "curvature": 0.04,
                "species": ["songbirds", "waterfowl"],
                "weight_spring": 0.48,
                "weight_fall": 0.55,
                "weight_default": 0.50,
            },
            {
                "name": "East Asian raptor route",
                "angle_deg": 195,
                "sigma": 0.08,
                "curvature": 0.03,
                "species": ["raptors"],
                "weight_spring": 0.50,
                "weight_fall": 0.55,
                "weight_default": 0.48,
            },
        ],
        "species": {
            "songbirds": {
                "label": "Passerines (buntings/flycatchers)",
                "color": [255, 165, 0],
                "color_pub": [230, 150, 40],
                "arrow_count": 50,
                "sigma": 16,
                "arrow_width": 5,
                "arrow_length": 56,
                "alpha": 150,
            },
            "waterfowl": {
                "label": "Waterfowl / shorebirds",
                "color": [60, 200, 255],
                "color_pub": [80, 170, 210],
                "arrow_count": 48,
                "sigma": 15,
                "arrow_width": 5,
                "arrow_length": 56,
                "alpha": 150,
            },
            "raptors": {
                "label": "Raptors (kites/hawks)",
                "color": [255, 60, 60],
                "color_pub": [210, 80, 80],
                "arrow_count": 24,
                "sigma": 10,
                "arrow_width": 6,
                "arrow_length": 62,
                "alpha": 160,
            },
            "local": {
                "label": "Local/resident birds",
                "color": [60, 255, 140],
                "color_pub": [90, 210, 150],
            },
        },
        "monthly_calendar": [
            {"month": "Jan", "migration_index": 0.05, "intensity": 0.10, "label": "Winter", "season": "winter"},
            {"month": "Feb", "migration_index": 0.06, "intensity": 0.12, "label": "Winter", "season": "winter"},
            {"month": "Mar", "migration_index": 0.30, "intensity": 0.42, "label": "Spring build-up", "season": "spring"},
            {"month": "Apr", "migration_index": 0.68, "intensity": 0.82, "label": "Spring peak", "season": "spring"},
            {"month": "May", "migration_index": 0.78, "intensity": 0.95, "label": "Spring peak", "season": "spring"},
            {"month": "Jun", "migration_index": 0.14, "intensity": 0.18, "label": "Summer", "season": "summer"},
            {"month": "Jul", "migration_index": 0.10, "intensity": 0.14, "label": "Summer", "season": "summer"},
            {"month": "Aug", "migration_index": 0.38, "intensity": 0.38, "label": "Late summer", "season": "summer"},
            {"month": "Sep", "migration_index": 0.70, "intensity": 0.88, "label": "Fall peak", "season": "fall"},
            {"month": "Oct", "migration_index": 0.82, "intensity": 0.96, "label": "Fall peak", "season": "fall"},
            {"month": "Nov", "migration_index": 0.28, "intensity": 0.42, "label": "Fall winding down", "season": "fall"},
            {"month": "Dec", "migration_index": 0.06, "intensity": 0.10, "label": "Winter", "season": "winter"},
        ],
    },
}

SEASON_DEFAULTS = {
    "winter": {
        "months": [12, 1, 2],
        "migration_intensity": 0.20,
        "resident_fraction": 0.85,
        "night_fraction": 0.45,
        "weather_risk": 1.10,
    },
    "spring": {
        "months": [3, 4, 5],
        "migration_intensity": 1.00,
        "resident_fraction": 0.45,
        "night_fraction": 0.60,
        "weather_risk": 1.20,
    },
    "summer": {
        "months": [6, 7, 8],
        "migration_intensity": 0.25,
        "resident_fraction": 0.75,
        "night_fraction": 0.40,
        "weather_risk": 1.00,
    },
    "fall": {
        "months": [9, 10, 11],
        "migration_intensity": 0.90,
        "resident_fraction": 0.50,
        "night_fraction": 0.65,
        "weather_risk": 1.25,
    },
}


def available_flyways() -> Dict[str, str]:
    """Return {key: label} for all available flyway presets."""
    return {k: v["label"] for k, v in FLYWAY_PRESETS.items()}


def get_flyway(name: str) -> Dict[str, Any]:
    """Get a flyway preset by name. Raises KeyError if not found."""
    if name not in FLYWAY_PRESETS:
        available = ", ".join(FLYWAY_PRESETS.keys())
        raise KeyError(f"Unknown flyway '{name}'. Available: {available}")
    return FLYWAY_PRESETS[name]
